apiVersion: v1
kind: Service
metadata:
  name: autostack-backend
  namespace: autostack
  labels:
    app: autostack
    component: backend
spec:
  type: ClusterIP
  selector:
    app: autostack
    component: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
