apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autostack-db-pvc
  namespace: autostack
  labels:
    app: autostack
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Change based on your cloud provider
