apiVersion: v1
kind: Service
metadata:
  name: autostack-db
  namespace: autostack
  labels:
    app: autostack
    component: database
spec:
  type: ClusterIP
  selector:
    app: autostack
    component: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  sessionAffinity: None
