apiVersion: v1
kind: Service
metadata:
  name: autostack-frontend
  namespace: autostack
  labels:
    app: autostack
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: autostack
    component: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
